### ISSUE TITLE
Mapping API

### ISSUE THREAD

**Issue by kcphysics** [roblevesque/webglmapview#4]
This is more of a request than an issue.

I see that the map is basically a JS spa today, doing all calculations client side, but I was wondering if it would be possible/prudent to create an REST API for some of the functions?

Not sure what the hosting setup is, but I use `tintin++` as a client, and that means by default I don't have access to Qon's plugin.  I am working on a python port of it, but if you had an API, that would be a synch.

Wondering if this is something you'd consider.  If so, I'd definitely volunteer helping to develop it/implement it.

**Comment by roblevesque** [comment]
The map is currently being hosted in Github pages & the map is all done via JS because I don't have a way of actually hosting it. Even if I did, I'd likely still host it the same way since there really is no need for a proper backend. 

With that being said, there is absolutely a way to develop an API like interface as it stands. There just wouldn't be any data storage possible. It would just be querying data and asking for whatever information you want. I'm not sure if this would be of any  real benefit when it would be faster (and likely better quality) if done in python.

**Comment by roblevesque** [comment]
I'm going to close this, unless you have more to discuss on it. I'd be willing to api-ify  some of the things if you want to ask for some specific items.
